[package]
name = "sandforge"
version = "0.1.0"
edition = "2021"

[features]
bench = []
dirty_chunk_rendering = []
chunk_border_rendering = []
multithreading = []

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false

[profile.release-debugged]
inherits = "release"
incremental = true
debug = true

[profile.optimized]
inherits = "release"
panic = "abort"
codegen-units = 1
lto = true

[dependencies]
winit = "0.28.6"
env_logger = "0.10"
error-iter = "0.4.1"
log = "0.4"
rand = { version = "0.8.4", features = ["small_rng"] }
dashmap = { version = "5.5.1", features = ["inline"] }
fps_counter = "2.0.0"
parking_lot = { version = "0.12.1", features = ["deadlock_detection"] }
bytemuck = "1.13.1"
earcutr = "0.4.2"
threadpool = "1.8.1"
ahash = "0.8.3"
rapier2d = "0.17.2"
cdt = "0.1.0"
lazy_static = "1.4.0"
serde_yaml = "0.9.25"
serde = { version = "1.0.188", features = ["derive"] }
pretty_env_logger = "0.5.0"
poly2tri-rs = "0.1.2"
bitflags = "2.4.0"
rayon = "1.8.0"
fastrand = "2.0.1"
wgpu = "0.17.1"
egui-wgpu = "0.23.0"
egui-winit = "0.23.0"
epaint = "0.23.0"
pollster = "0.3.0"
winit_input_helper = "0.14.1"
notify = "6.1.1"
noise = "0.8.2"
compact_str = { version = "0.7.1", features = ["serde"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"
